Repository scoutapp/scout-apm-php, pull requests merged in 2019-12, with the labels that each got.

#117 Improvements to API and logging/debugging
  CHANGELOG.md
  README.md
  src/Agent.php
  src/Connector/Connector.php
  src/Connector/SocketConnector.php
  src/CoreAgent/AutomaticDownloadAndLaunchManager.php
  src/CoreAgent/Downloader.php
  src/CoreAgent/Manifest.php
  src/Events/Request/Request.php
  src/Events/Span/Span.php
  src/Helper/RecursivelyCountSpans.php
  tests/Integration/MessageCapturingConnectorDelegator.php
  tests/Unit/AgentTest.php
  tests/Unit/Events/Request/RequestTest.php
  tests/Unit/Events/Span/SpanTest.php
  tests/Unit/Helper/RecursivelyCountSpansTest.php
Labels: BC BREAK, enhancement

#118 Added detection of /etc/alpine-release to determine if musl is used
  CHANGELOG.md
  src/Config.php
  src/Config/Source/DerivedSource.php
  src/Helper/LibcDetection.php
  tests/Unit/Config/Source/DerivedSourceTest.php
  tests/Unit/Helper/LibcDetectionTest.php
Labels: enhancement

#122 Explicit comment about intentionally different env var name
  tests/Integration/AgentTest.php
Labels: enhancement

#124 Fix warning on failed socket_connect
  phpunit.xml.dist
  src/Connector/SocketConnector.php
Labels: bug

#126 Fixing bug where data is not being displayed from Laravel app
  src/Helper/Backtrace.php
Labels: WIP, bug

#127 Update CoreAgent version to 1.2.6, with several bug fixes:
  src/Config/Source/DefaultSource.php
Labels: enhancement

#123 Send metadata less often
  CHANGELOG.md
  README.md
  composer.json
  composer.lock
  src/Agent.php
  src/Cache/DevNullCache.php
  tests/Integration/AgentTest.php
  tests/Unit/Cache/DevNullCacheTest.php
Labels: BC BREAK, enhancement

#131 Added PHP 7.4 support to CI build
  .travis.yml
Labels: enhancement

#130 Correctly handle warnings when reading manifest and cleaning download locks
  src/CoreAgent/Downloader.php
  src/CoreAgent/Manifest.php
Labels: bug

#134 Catch exceptions raised whilst sending metadata
  src/Agent.php
  tests/Unit/AgentTest.php
Labels: bug

#133 Default SCM subdirectory to null
  src/Events/Metadata.php
  tests/Unit/Events/MetadataTest.php
Labels: bug

#137 Reset request after send
  src/Agent.php
  tests/Unit/AgentTest.php
Labels: enhancement

#141 Only tag args if there are any
  src/Agent.php
  src/Events/Tag/Tag.php
  src/Extension/RecordedCall.php
  tests/Integration/AgentTest.php
Labels: enhancement

#140 Increased core version to 1.2.7
  src/Config/Source/DefaultSource.php
Labels: bug

#144 Wrap socket calls with error handler
  src/Connector/SocketConnector.php
  tests/Unit/Connector/SocketConnectorTest.php
Labels: enhancement

#145 Check empty string socket read & only Register once
  src/Agent.php
  src/Connector/Exception/FailedToSendCommand.php
  src/Connector/SocketConnector.php
  tests/Unit/AgentTest.php
Labels: bug

#146 Do not preemptively try to connect if monitoring is disabled
  src/Agent.php
  src/Connector/SocketConnector.php
  tests/Integration/AgentTest.php
Labels: bug

#148 Expose new ScoutApmAgent endpoint to start a new request
  CHANGELOG.md
  src/Agent.php
  src/ScoutApmAgent.php
  tests/Unit/AgentTest.php
Labels: BC BREAK, enhancement

#150 Made framework and framework version come from configuration
  src/Config/ConfigKey.php
  src/Events/Metadata.php
  tests/Unit/Events/MetadataTest.php
Labels: enhancement

#149 Capture request queue time
  src/Events/Request/Request.php
  src/Events/Tag/Tag.php
  src/Helper/FetchRequestHeaders.php
  src/Helper/Timer.php
  tests/Unit/Events/Request/RequestTest.php
  tests/Unit/Helper/FetchRequestHeadersTest.php
  tests/Unit/Helper/TimerTest.php
Labels: enhancement

#152 Improve test coverage for Agent
  .gitignore
  Makefile
  src/Agent.php
  tests/Unit/AgentTest.php
Labels: enhancement

#151 Check extension version is recent
  src/Agent.php
  src/Events/Metadata.php
  src/Extension/ExtentionCapabilities.php
  src/Extension/PotentiallyAvailableExtensionCapabilities.php
  src/Extension/Version.php
  tests/Integration/AgentTest.php
  tests/Integration/TestHelper.php
  tests/Unit/AgentTest.php
  tests/Unit/Events/MetadataTest.php
  tests/Unit/Extension/PotentiallyAvailableExtensionCapabilitiesTest.php
  tests/Unit/Extension/VersionTest.php
Labels: enhancement
